[project]
name = "MQTTReader"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "paho-mqtt>=2.1.0",
    "pandas>=2.3.3",
    "pydantic>=2.12.4",
    "rich>=14.2.0",
]
